# +-------------------------------------------------------------+
# |                    ConduitFly Plugin Settings               |
# |  Configure GUI, conduit behavior, crafting, visuals, and    |
# |  rank mechanics. After editing, use /conduitfly reload.     |
# +-------------------------------------------------------------+

# GUI Settings for the Rank Menu
rank-gui:
  item-slots: [ 10, 12, 14, 16 ]                    # Slot positions for rank buttons
  active-rank-material: "LIME_DYE"                # Material shown for the player's current rank
  inactive-rank-material: "LIGHT_GRAY_DYE"        # Material shown for ranks not yet unlocked
  filler-material: "GRAY_STAINED_GLASS_PANE"      # Background filler for unused slots
  bottom-bar-material: "BLACK_STAINED_GLASS_PANE" # Bottom row decoration

  previous-page-material: "ARROW"               # Item to go to the previous page
  next-page-material: "ARROW"                   # Item to go to the next page

# The block material used as a "Conduit"
conduit:
  material: "CONDUIT"

# Enables or disables the custom crafting recipe for the conduit item
custom-recipe: false

# Custom crafting recipe shape and ingredients for the conduit material
conduit-recipe:
  shape:
    - "GGG"
    - "EHE"
    - "GGG"
  ingredients:
    G: PRISMARINE_CRYSTALS
    E: NAUTILUS_SHELL
    H: HEART_OF_THE_SEA

# Visual particle effects that indicate the active conduit area
particles:
  # The particle effect to use.
  # See full list here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  type: "END_ROD"
  # Delay in ticks between particle updates (20 ticks = 1 second)
  delay: 35

  # Only applies to colorable particles like DUST
  color:
    # 0 - 255
    red: 0
    green: 5
    blue: 155

  size: 10.0           # Size of the particle (only applies to DUST particles)

# Rank Settings
# Each rank is linked to a permission node and has customizable stats.
# The display order in menus follows the order listed here.
ranks:
  default:
    permission: "conduitfly.default"
    radius: 10.0                   # Horizontal range of conduit effect
    duration: 3                    # Flight duration in seconds
    prevent-fall-damage: false     # Should fall damage be prevented?
    price: 60                      # Cost to upgrade to the next rank
    display-name: "Default"        # Displayed name in GUI menus

  level1:
    permission: "conduitfly.level1"
    radius: 15.0
    duration: 5
    prevent-fall-damage: false
    price: 100
    display-name: "Level 1"

  level2:
    permission: "conduitfly.level2"
    radius: 20.0
    duration: 10
    prevent-fall-damage: false
    price: 1000
    display-name: "VIP"

  level3:
    permission: "conduitfly.level3"
    radius: 25.0
    duration: 15
    prevent-fall-damage: true
    price: 1500
    display-name: "Admin"

  level4:
    permission: "conduitfly.level4"
    radius: 25.0
    duration: 20
    prevent-fall-damage: true
    price: 2000
    display-name: "OP"

  level5:
    permission: "conduitfly.level5"
    radius: 30.0
    duration: 30
    prevent-fall-damage: true
    price: 5000
    display-name: "OP+"

# Storage settings
# Choose how data is stored: either "mysql" or "sqlite"
#!!! If you're not sure what this is for, do not change these settings. !!!
storage:
  type: sqlite  # Options: mysql or sqlite

  mysql:
    host: localhost
    port: 3306
    database: conduitfly
    username: root
    password: ""

  sqlite:
    file: conduits.db