name: ConduitFly
version: '1.1.0'
main: org.ogsammaenr.conduitFly.ConduitFly
api-version: '1.21'
depend:
  - Vault
  - BentoBox
commands:
  conduitfly:
    description: ConduitFly ana komutu
    usage: /<command> [reload|help|rankup|area]
    permission: conduitfly.use
    permission-message: §cBu komutu kullanmak için yetkin yok.