#   permlerin isimleri ve adedi değiştirilebilir
#
#     **example perm**
#  yourPermission:
#    permission: "conduitfly.yourPermission"
#    radius: 20.0
#    duration: 15
#    prevent-fall-damage: true
#

ranks:
  default: #                                Oyuncunun hiçbir yetkisi yoksa çalışır
    permission: "conduitfly.default"  #     zorunlu
    radius: 10.5
    duration: 5
    prevent-fall-damage: false
    price:
  level1:
    permission: "conduitfly.level1"
    radius: 20.0
    duration: 15
    prevent-fall-damage: false
    price:
  level2:
    permission: "conduitfly.level2"
    radius: 40.0
    duration: 30
    prevent-fall-damage: true
    price:
  level3:
    permission: "conduitfly.level3"
    radius: 40.0
    duration: 30
    prevent-fall-damage: true
    price:
  level4:
    permission: "conduitfly.level4"
    radius: 40.0
    duration: 30
    prevent-fall-damage: true
    price:

conduit:
  material: "CONDUIT"