ranks:
  default:
    permission: "conduitfly.default"
    radius: 10.5
    duration: 10
    prevent-fall-damage: true
  vip:
    permission: "conduitfly.vip"
    radius: 20.0
    duration: 15
    prevent-fall-damage: true
  elite:
    permission: "conduitfly.elite"
    radius: 40.0
    duration: 30
    prevent-fall-damage: false

conduit:
  material: "CONDUIT"